{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "owncast.fullname" . }}
  labels:
    {{- include "owncast.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.config | quote }}
{{- end }}
