apiVersion: v1
kind: Service
metadata:
  name: {{ include "owncast.fullname" . }}-web
  labels:
    {{- include "owncast.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "owncast.selectorLabels" . | nindent 4 }}
{{- if .Values.service.web.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.web.loadBalancerIP }}
{{- end }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "owncast.fullname" . }}-rtmp
  labels:
    {{- include "owncast.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.rtmp.type }}
  ports:
    - port: {{ .Values.service.rtmp.port }}
      targetPort: rtmp
      protocol: TCP
      name: rtmp
  selector:
    {{- include "owncast.selectorLabels" . | nindent 4 }}
{{- if .Values.service.rtmp.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.rtmp.loadBalancerIP }}
{{- end }}
